export const UPDATE_UI = 'UPDATE_UI'

export const OPEN_SIZE_TABLE_DIALOG = 'OPEN_SIZE_TABLE_DIALOG'
export const CLOSE_SIZE_TABLE_DIALOG = 'CLOSE_SIZE_TABLE_DIALOG'

export const OPEN_ADD_TO_BAG_DIALOG = 'OPEN_ADD_TO_BAG_DIALOG'
export const CLOSE_ADD_TO_BAG_DIALOG = 'CLOSE_ADD_TO_BAG_DIALOG'
